import CoreGraphics
import Foundation

#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif

/// Instant placeholder decoded from `Asset.thumbhash` — brief task 2, first pipeline stage.
/// Pure-Swift port of the reference `thumbHashToRGBA` /
/// `thumbHashToApproximateAspectRatio` (`server/node_modules/thumbhash`), verified byte-for-byte
/// against it in `ThumbHashTests` via golden vectors generated by that implementation.
public struct ThumbHashImage: Sendable, Hashable {
  public var width: Int
  public var height: Int
  /// Row-major, non-premultiplied RGBA bytes, `width * height * 4` elements.
  public var rgba: [UInt8]

  public init(width: Int, height: Int, rgba: [UInt8]) {
    self.width = width
    self.height = height
    self.rgba = rgba
  }

  /// Platform image for grid placeholders (viewers), via `makeCGImage`.
  #if canImport(UIKit)
  public func makePlatformImage() -> UIImage? {
    makeCGImage().map(UIImage.init(cgImage:))
  }
  #elseif canImport(AppKit)
  public func makePlatformImage() -> NSImage? {
    makeCGImage().map { NSImage(cgImage: $0, size: NSZeroSize) }
  }
  #endif

  /// Raw decoded bitmap. The bytes are non-premultiplied RGBA (`alphaLast`).
  public func makeCGImage() -> CGImage? {
    let data = Data(rgba)
    guard
      let provider = CGDataProvider(data: data as CFData),
      let space = CGColorSpace(name: CGColorSpace.sRGB)
    else { return nil }
    return CGImage(
      width: width,
      height: height,
      bitsPerComponent: 8,
      bitsPerPixel: 32,
      bytesPerRow: width * 4,
      space: space,
      bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.last.rawValue),
      provider: provider,
      decode: nil,
      shouldInterpolate: false,
      intent: .defaultIntent
    )
  }
}

public enum ThumbHashError: Error, Sendable, Equatable {
  case invalidBase64
  case truncated
}

public enum ThumbHash {
  /// Decodes the base64 (or base64url) thumbhash stored on `Asset.thumbhash`.
  public static func decode(base64: String) throws -> ThumbHashImage {
    var normalized =
      base64
      .replacingOccurrences(of: "-", with: "+")
      .replacingOccurrences(of: "_", with: "/")
    let remainder = normalized.count % 4
    if remainder != 0 {
      normalized += String(repeating: "=", count: 4 - remainder)
    }
    guard let data = Data(base64Encoded: normalized, options: .ignoreUnknownCharacters) else {
      throw ThumbHashError.invalidBase64
    }
    return try decode(bytes: Array(data))
  }

  public static func decode(bytes: [UInt8]) throws -> ThumbHashImage {
    guard bytes.count >= 5 else { throw ThumbHashError.truncated }

    let header24 = Int(bytes[0]) | (Int(bytes[1]) << 8) | (Int(bytes[2]) << 16)
    let header16 = Int(bytes[3]) | (Int(bytes[4]) << 8)
    let lDC = Double(header24 & 63) / 63
    let pDC = Double((header24 >> 6) & 63) / 31.5 - 1
    let qDC = Double((header24 >> 12) & 63) / 31.5 - 1
    let lScale = Double((header24 >> 18) & 31) / 31
    let hasAlpha = (header24 >> 23) != 0
    let pScale = Double((header16 >> 3) & 63) / 63
    let qScale = Double((header16 >> 9) & 63) / 63
    let isLandscape = (header16 >> 15) != 0
    let lx = max(3, isLandscape ? (hasAlpha ? 5 : 7) : (header16 & 7))
    let ly = max(3, isLandscape ? (header16 & 7) : (hasAlpha ? 5 : 7))

    // Nibble budget the decoder below consumes; a shorter hash is corrupt, not "empty".
    // Bounds mirror `decodeChannel` exactly (the reference keeps a triangular DCT subset).
    let channelCount: (Int, Int) -> Int = { nx, ny in
      var n = 0
      for cy in 0..<ny {
        var cx = cy == 0 ? 1 : 0
        while cx * ny < nx * (ny - cy) {
          n += 1
          cx += 1
        }
      }
      return n
    }
    let acStart = hasAlpha ? 6 : 5
    let acCount =
      channelCount(lx, ly) + channelCount(3, 3) + channelCount(3, 3)
      + (hasAlpha ? channelCount(5, 5) : 0)
    guard bytes.count >= acStart + (acCount + 1) / 2 else { throw ThumbHashError.truncated }
    if hasAlpha, bytes.count < 6 { throw ThumbHashError.truncated }
    let aDC = hasAlpha ? Double(bytes[5] & 15) / 15 : 1
    let aScale = hasAlpha ? Double(bytes[5] >> 4) / 15 : 0

    var acIndex = 0
    let decodeChannel: (Int, Int, Double) -> [Double] = { nx, ny, scale in
      var ac: [Double] = []
      ac.reserveCapacity(nx * ny - 1)
      for cy in 0..<ny {
        var cx = cy == 0 ? 1 : 0
        while cx * ny < nx * (ny - cy) {
          let byte = Int(bytes[acStart + (acIndex >> 1)])
          let nibble = (byte >> ((acIndex & 1) << 2)) & 15
          ac.append((Double(nibble) / 7.5 - 1) * scale)
          acIndex += 1
          cx += 1
        }
      }
      return ac
    }
    let lAC = decodeChannel(lx, ly, lScale)
    let pAC = decodeChannel(3, 3, pScale * 1.25)
    let qAC = decodeChannel(3, 3, qScale * 1.25)
    let aAC: [Double] = hasAlpha ? decodeChannel(5, 5, aScale) : []

    let ratio = approximateAspectRatio(bytes: bytes)
    let w = Int((ratio > 1 ? 32 : 32 * ratio).rounded())
    let h = Int((ratio > 1 ? 32 / ratio : 32).rounded())
    var rgba = [UInt8](repeating: 0, count: w * h * 4)
    var fx = [Double](repeating: 0, count: max(lx, hasAlpha ? 5 : 3))
    var fy = [Double](repeating: 0, count: max(ly, hasAlpha ? 5 : 3))
    for y in 0..<h {
      for x in 0..<w {
        var l = lDC, p = pDC, q = qDC, a = aDC

        for cx in 0..<fx.count {
          fx[cx] = cos(Double.pi / Double(w) * (Double(x) + 0.5) * Double(cx))
        }
        for cy in 0..<fy.count {
          fy[cy] = cos(Double.pi / Double(h) * (Double(y) + 0.5) * Double(cy))
        }

        var j = 0
        for cy in 0..<ly {
          let fy2 = fy[cy] * 2
          var cx = cy == 0 ? 1 : 0
          while cx * ly < lx * (ly - cy) {
            l += lAC[j] * fx[cx] * fy2
            j += 1
            cx += 1
          }
        }

        j = 0
        for cy in 0..<3 {
          let fy2 = fy[cy] * 2
          var cx = cy == 0 ? 1 : 0
          while cx < 3 - cy {
            let f = fx[cx] * fy2
            p += pAC[j] * f
            q += qAC[j] * f
            j += 1
            cx += 1
          }
        }

        if hasAlpha {
          j = 0
          for cy in 0..<5 {
            let fy2 = fy[cy] * 2
            var cx = cy == 0 ? 1 : 0
            while cx < 5 - cy {
              a += aAC[j] * fx[cx] * fy2
              j += 1
              cx += 1
            }
          }
        }

        let b = l - 2.0 / 3.0 * p
        let r = (3 * l - b + q) / 2
        let g = r - q
        let o = (y * w + x) * 4
        rgba[o] = UInt8(max(0, min(1, r)) * 255)
        rgba[o + 1] = UInt8(max(0, min(1, g)) * 255)
        rgba[o + 2] = UInt8(max(0, min(1, b)) * 255)
        rgba[o + 3] = UInt8(max(0, min(1, a)) * 255)
      }
    }
    return ThumbHashImage(width: w, height: h, rgba: rgba)
  }

  /// Width / height of the encoded image, for sizing the placeholder before decoding.
  public static func approximateAspectRatio(base64: String) throws -> Double {
    var normalized =
      base64
      .replacingOccurrences(of: "-", with: "+")
      .replacingOccurrences(of: "_", with: "/")
    let remainder = normalized.count % 4
    if remainder != 0 {
      normalized += String(repeating: "=", count: 4 - remainder)
    }
    guard let data = Data(base64Encoded: normalized, options: .ignoreUnknownCharacters) else {
      throw ThumbHashError.invalidBase64
    }
    return approximateAspectRatio(bytes: Array(data))
  }

  static func approximateAspectRatio(bytes: [UInt8]) -> Double {
    guard bytes.count >= 5 else { return 1 }
    let header = Int(bytes[3])
    let hasAlpha = bytes[2] & 0x80
    let isLandscape = bytes[4] & 0x80
    let lx = isLandscape != 0 ? (hasAlpha != 0 ? 5 : 7) : (header & 7)
    let ly = isLandscape != 0 ? (header & 7) : (hasAlpha != 0 ? 5 : 7)
    guard lx > 0, ly > 0 else { return 1 }
    return Double(lx) / Double(ly)
  }
}
