-- NOTE: This file is auto generated by ./sql-generator

-- MemoryRepository.statistics
select
  count(*) as "total"
from
  "memory"
where
  "deletedAt" is null
  and "ownerId" = $1

-- MemoryRepository.statistics (date filter)
select
  count(*) as "total"
from
  "memory"
where
  (
    "showAt" is null
    or "showAt" <= $1
  )
  and (
    "hideAt" is null
    or "hideAt" >= $2
  )
  and "deletedAt" is null
  and "ownerId" = $3

-- MemoryRepository.search
select
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and (
            (
              "asset"."ownerId" = $1
              and "asset"."spaceId" is null
              and "asset"."libraryId" is null
            )
            or exists (
              select
                "shared_space_member"."spaceId"
              from
                "shared_space_member"
              where
                "shared_space_member"."spaceId" = "asset"."spaceId"
                and "shared_space_member"."userId" = $2
            )
            or exists (
              select
                "library"."id"
              from
                "library"
                left join "library_member" on "library_member"."libraryId" = "library"."id"
                and "library_member"."userId" = $3
              where
                "library"."id" = "asset"."libraryId"
                and (
                  "library"."ownerId" = $4
                  or "library_member"."userId" = $5
                )
            )
          )
          and not exists (
            select
              $6 as "one"
            from
              "asset_face"
              inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
              and "person"."ownerId" = "asset"."ownerId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $7
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets",
  "memory".*
from
  "memory"
where
  "deletedAt" is null
  and "ownerId" = $8
order by
  "showAt" desc nulls last,
  "memoryAt" desc

-- MemoryRepository.search (date filter)
select
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and (
            (
              "asset"."ownerId" = $1
              and "asset"."spaceId" is null
              and "asset"."libraryId" is null
            )
            or exists (
              select
                "shared_space_member"."spaceId"
              from
                "shared_space_member"
              where
                "shared_space_member"."spaceId" = "asset"."spaceId"
                and "shared_space_member"."userId" = $2
            )
            or exists (
              select
                "library"."id"
              from
                "library"
                left join "library_member" on "library_member"."libraryId" = "library"."id"
                and "library_member"."userId" = $3
              where
                "library"."id" = "asset"."libraryId"
                and (
                  "library"."ownerId" = $4
                  or "library_member"."userId" = $5
                )
            )
          )
          and not exists (
            select
              $6 as "one"
            from
              "asset_face"
              inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
              and "person"."ownerId" = "asset"."ownerId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $7
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets",
  "memory".*
from
  "memory"
where
  (
    "showAt" is null
    or "showAt" <= $8
  )
  and (
    "hideAt" is null
    or "hideAt" >= $9
  )
  and "deletedAt" is null
  and "ownerId" = $10
order by
  "showAt" desc nulls last,
  "memoryAt" desc

-- MemoryRepository.search (upcoming filter)
select
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and (
            (
              "asset"."ownerId" = $1
              and "asset"."spaceId" is null
              and "asset"."libraryId" is null
            )
            or exists (
              select
                "shared_space_member"."spaceId"
              from
                "shared_space_member"
              where
                "shared_space_member"."spaceId" = "asset"."spaceId"
                and "shared_space_member"."userId" = $2
            )
            or exists (
              select
                "library"."id"
              from
                "library"
                left join "library_member" on "library_member"."libraryId" = "library"."id"
                and "library_member"."userId" = $3
              where
                "library"."id" = "asset"."libraryId"
                and (
                  "library"."ownerId" = $4
                  or "library_member"."userId" = $5
                )
            )
          )
          and not exists (
            select
              $6 as "one"
            from
              "asset_face"
              inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
              and "person"."ownerId" = "asset"."ownerId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $7
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets",
  "memory".*
from
  "memory"
where
  "showAt" > $8
  and "deletedAt" is null
  and "ownerId" = $9
order by
  "showAt" desc nulls last,
  "memoryAt" desc

-- MemoryRepository.search (not upcoming filter)
select
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and (
            (
              "asset"."ownerId" = $1
              and "asset"."spaceId" is null
              and "asset"."libraryId" is null
            )
            or exists (
              select
                "shared_space_member"."spaceId"
              from
                "shared_space_member"
              where
                "shared_space_member"."spaceId" = "asset"."spaceId"
                and "shared_space_member"."userId" = $2
            )
            or exists (
              select
                "library"."id"
              from
                "library"
                left join "library_member" on "library_member"."libraryId" = "library"."id"
                and "library_member"."userId" = $3
              where
                "library"."id" = "asset"."libraryId"
                and (
                  "library"."ownerId" = $4
                  or "library_member"."userId" = $5
                )
            )
          )
          and not exists (
            select
              $6 as "one"
            from
              "asset_face"
              inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
              and "person"."ownerId" = "asset"."ownerId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $7
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets",
  "memory".*
from
  "memory"
where
  (
    "showAt" is null
    or "showAt" <= $8
  )
  and "deletedAt" is null
  and "ownerId" = $9
order by
  "showAt" desc nulls last,
  "memoryAt" desc

-- MemoryRepository.get
select
  "memory".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and (
            (
              "asset"."ownerId" = "memory"."ownerId"
              and "asset"."spaceId" is null
              and "asset"."libraryId" is null
            )
            or exists (
              select
                "shared_space_member"."spaceId"
              from
                "shared_space_member"
              where
                "shared_space_member"."spaceId" = "asset"."spaceId"
                and "shared_space_member"."userId" = "memory"."ownerId"
            )
            or exists (
              select
                "library"."id"
              from
                "library"
                left join "library_member" on "library_member"."libraryId" = "library"."id"
                and "library_member"."userId" = "memory"."ownerId"
              where
                "library"."id" = "asset"."libraryId"
                and (
                  "library"."ownerId" = "memory"."ownerId"
                  or "library_member"."userId" = "memory"."ownerId"
                )
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets"
from
  "memory"
where
  "id" = $1
  and "deletedAt" is null

-- MemoryRepository.update
update "memory"
set
  "ownerId" = $1,
  "isSaved" = $2
where
  "id" = $3
select
  "memory".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and (
            (
              "asset"."ownerId" = "memory"."ownerId"
              and "asset"."spaceId" is null
              and "asset"."libraryId" is null
            )
            or exists (
              select
                "shared_space_member"."spaceId"
              from
                "shared_space_member"
              where
                "shared_space_member"."spaceId" = "asset"."spaceId"
                and "shared_space_member"."userId" = "memory"."ownerId"
            )
            or exists (
              select
                "library"."id"
              from
                "library"
                left join "library_member" on "library_member"."libraryId" = "library"."id"
                and "library_member"."userId" = "memory"."ownerId"
              where
                "library"."id" = "asset"."libraryId"
                and (
                  "library"."ownerId" = "memory"."ownerId"
                  or "library_member"."userId" = "memory"."ownerId"
                )
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets"
from
  "memory"
where
  "id" = $1
  and "deletedAt" is null

-- MemoryRepository.delete
delete from "memory"
where
  "id" = $1

-- MemoryRepository.getAssetIds
select
  "assetId"
from
  "memory_asset"
where
  "memoriesId" = $1
  and "assetId" in ($2)

-- MemoryRepository.addAssetIds
insert into
  "memory_asset" ("memoriesId", "assetId")
values
  ($1, $2)
